In [1]:
import pandas as pd
import numpy as np

#data = pd.read_csv('data_python2.csv', index_col=0)
#V = data['Visible'].values


#states = PATH1, PATH2, PATH3, PATH4 = 0, 1, 2, 3

V = np.array([3, 3, 2, 1, 2, 2, 1, 2, 3, 0])

# Transition Probabilities
A = np.array(((0.3, 0.2, 0.2, 0.3), (0.2, 0.3, 0.2, 0.3), (0.2, 0.2, 0.3, 0.3), (0.2, 0.2, 0.2, 0.4)))

# Emission Probabilities
B = np.array(((0.3, 0.3, 0.3, 0.1), (0.3, 0.3, 0.3, 0.1), (0.3, 0.3, 0.3, 0.1), (0.1, 0.1, 0.1, 0.7)))

# Equal Probabilities for the initial distribution
pi = np.array((0.2, 0.2, 0.2, 0.4))


def backward(V, A, B):
    beta = np.zeros((V.shape[0], A.shape[0]))

    # setting beta(T) = 1
    beta[V.shape[0] - 1] = np.ones((A.shape[0]))

    # Loop in backward way from T-1 to
    # Due to python indexing the actual loop will be T-2 to 0
    for t in range(V.shape[0] - 2, -1, -1):
        for j in range(A.shape[0]):
            beta[t, j] = (beta[t + 1] * B[:, V[t + 1]]).dot(A[j, :])

    return beta


beta = backward(V, A, B)
print(beta)

[[3.06232167e-06 3.06232167e-06 3.06232167e-06 3.69278282e-06]
 [1.17093821e-05 1.17093821e-05 1.17093821e-05 1.06793567e-05]
 [4.93315275e-05 4.93315275e-05 4.93315275e-05 4.49920450e-05]
 [2.07833250e-04 2.07833250e-04 2.07833250e-04 1.89551500e-04]
 [8.75595000e-04 8.75595000e-04 8.75595000e-04 7.98610000e-04]
 [3.68850000e-03 3.68850000e-03 3.68850000e-03 3.36700000e-03]
 [1.55100000e-02 1.55100000e-02 1.55100000e-02 1.43800000e-02]
 [6.30000000e-02 6.30000000e-02 6.30000000e-02 7.60000000e-02]
 [2.40000000e-01 2.40000000e-01 2.40000000e-01 2.20000000e-01]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00]]


In [6]:
V

array([3, 3, 2, 1, 2, 2, 1, 2, 3, 0])

In [2]:
A

array([[0.3, 0.2, 0.2, 0.3],
       [0.2, 0.3, 0.2, 0.3],
       [0.2, 0.2, 0.3, 0.3],
       [0.2, 0.2, 0.2, 0.4]])

In [3]:
pi

array([0.2, 0.2, 0.2, 0.4])