In [1]:
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
from pprint import pprint
%matplotlib inline


# create state space and initial state probabilities
states = [ 'Weight1' , 'Weight2' , 'Weight3', 'Weight4']
pi = [ 0.2 , 0.2 , 0.2, 0.4 ]


state_space = pd.Series ( pi , index = states , name = 'states' )
print ( state_space )
print ( state_space.sum ( ) )

# create transition matrix
# equals transition probability matrix of changing states given a state
# matrix is size (M x M) where M is number of states
q_df = pd.DataFrame ( columns = states , index = states )
q_df.loc [ states [ 0 ] ] = [ 0.3 , 0.2 , 0.2, 0.3 ]
q_df.loc [ states [ 1 ] ] = [ 0.2 , 0.3 , 0.2, 0.3 ]
q_df.loc [ states [ 2 ] ] = [ 0.2 , 0.2 , 0.3, 0.3 ]
q_df.loc [ states [ 3 ] ] = [ 0.2 , 0.2 , 0.2, 0.4 ]


print ( q_df )

q = q_df.values
print ( '\n' , q , q.shape , '\n')
print ( q_df.sum ( axis = 1 ) )

# create a function that maps transition probability dataframe
# to markov edges and weights
def _get_markov_edges( Q ) :
    edges = { }
    for col in Q.columns :
        for idx in Q.index :
            edges [ ( idx , col ) ] = Q.loc [ idx , col ]
    return edges

edges_wts = _get_markov_edges ( q_df )
pprint ( edges_wts )

# create graph object
G = nx.MultiDiGraph ( )

# nodes correspond to states
G.add_nodes_from ( states )
print ( f'Nodes:\n{G.nodes()}\n' )

# edges represent transition probabilities
for k , v in edges_wts.items ( ) :
    tmp_origin , tmp_destination = k [ 0 ] , k [ 1 ]
    G.add_edge ( tmp_origin , tmp_destination , weight = v , label= v )
print ( f'Edges:' )
pprint ( G.edges ( data = True ) )

pos = nx.drawing.nx_pydot.graphviz_layout(G, prog = 'dot')
#pos = nx.nx_pydot.graphviz_layout(G, prog='dot')
nx.draw_networkx ( G , pos )

# create edge labels for jupyter plot but is not necessary
edge_labels = { ( n1 , n2 ): d [ 'label' ] for n1 , n2 ,d in G.edges ( data = True ) }
nx.draw_networkx_edge_labels ( G , pos , edge_labels = edge_labels )
nx.drawing.nx_pydot.write_dot ( G , 'pet_dog_markov.dot' )

Weight1    0.2
Weight2    0.2
Weight3    0.2
Weight4    0.4
Name: states, dtype: float64
1.0
        Weight1 Weight2 Weight3 Weight4
Weight1     0.3     0.2     0.2     0.3
Weight2     0.2     0.3     0.2     0.3
Weight3     0.2     0.2     0.3     0.3
Weight4     0.2     0.2     0.2     0.4

 [[0.3 0.2 0.2 0.3]
 [0.2 0.3 0.2 0.3]
 [0.2 0.2 0.3 0.3]
 [0.2 0.2 0.2 0.4]] (4, 4) 

Weight1    1.0
Weight2    1.0
Weight3    1.0
Weight4    1.0
dtype: float64
{('Weight1', 'Weight1'): 0.3,
 ('Weight1', 'Weight2'): 0.2,
 ('Weight1', 'Weight3'): 0.2,
 ('Weight1', 'Weight4'): 0.3,
 ('Weight2', 'Weight1'): 0.2,
 ('Weight2', 'Weight2'): 0.3,
 ('Weight2', 'Weight3'): 0.2,
 ('Weight2', 'Weight4'): 0.3,
 ('Weight3', 'Weight1'): 0.2,
 ('Weight3', 'Weight2'): 0.2,
 ('Weight3', 'Weight3'): 0.3,
 ('Weight3', 'Weight4'): 0.3,
 ('Weight4', 'Weight1'): 0.2,
 ('Weight4', 'Weight2'): 0.2,
 ('Weight4', 'Weight3'): 0.2,
 ('Weight4', 'Weight4'): 0.4}
Nodes:
['Weight1', 'Weight2', 'Weight3', 'Weight4']

